### ISSUE TITLE
Layer api can become unresponsive

### ISSUE THREAD

**Issue by 4hlberg** [mimiro-io/oracle-datalayer#4]
Throws an error looking like the layer is unable to connect to the db, but in reality it is the layer not accepting get-requests.

needs more follow up.

Also should throw an error to the job log if this error occurs

**Comment by gra-moore** [comment]
@4hlberg  Is there any follow up on this? If not can it be closed?

**Comment by 4hlberg** [comment]
The issue remains, have not had the time to put a fix in place. Investigation leads to some errors not being propagated properly.

**Comment by 4hlberg** [comment]
Issue is obsolete with the new datalayer released in 0.2.2 and forwards.
